# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: Build the project
    jobs:
    - job: Build
      displayName: Build job
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
          addToPath: true
          architecture: 'x64'
      
      - script: |
          pip install -t ./ -r requirements.txt
      
      - script: |
          zip -r $(Build.ArtifactStagingDirectory)/lambda.zip . -x *.txt '*.git*' *.yml @
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'lambda.zip'
          publishLocation: 'Container'
          
  - stage: Deployment
    displayName: Deploy the project
    jobs:
      - job: Deployment
        displayName: Deploy job
        pool:
          vmImage: ubuntu-latest
        steps:
          - download: current
            artifact: lambda.zip
